### ISSUE TITLE
Create Issue Templates for Scipian Projects

### ISSUE THREAD

**Issue by ncronquist** [scipian/community#11]
As a user or contributor to the Scipian project, I would like to be able to create issues with different templates for different types of issues (bug vs feature vs question, etc.).

See [About Issue and Pull Request Templates][issue-templates] for more information on creating and using templates.

[issue-templates]: https://help.github.com/en/articles/about-issue-and-pull-request-templates

**Comment by dragan** [comment]
This is pretty self explanatory, marking this ready.
