### ISSUE TITLE
Create Code of Conduct doc

### ISSUE THREAD

**Issue by nicklathe** [scipian/community#13]

**Comment by ncronquist** [comment]
We should do some investigation around different codes of conduct in use, but I think we should take a look at the [Contributor Covenant](https://www.contributor-covenant.org/)

**Comment by dragan** [comment]
I feel this is ready and will drag it over. Who ever wants to work on it, make sure you estimate it.

**Comment by nicklathe** [comment]
Another one I like is the CNCF [Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md). Kubernetes uses this too, which they actually just link to. Could be a cool way of going, since we'd like to get Scipian adopted by the CNCF at some point?
