### ISSUE TITLE
Setup labels for each repo

### ISSUE THREAD

**Issue by dragan** [scipian/community#15]
Create the same set of labels for each repo that belongs to the Scipian organization

**Comment by dragan** [comment]
Initial thoughts on colors, should give us a good range for creating labels. I'd like to narrow down to one light blue and orange though.

<img width="51" alt="label-colors" src="https://user-images.githubusercontent.com/65690/30995282-fa7b9440-a46d-11e7-9943-14e2423823bb.png">

**Comment by dragan** [comment]
@weitenghuang and @nicklathe let's pair tomorrow and do our initial triage of issues and put our labels in place for each repo.

**Comment by weitenghuang** [comment]
Sounds good

**Comment by dragan** [comment]
## Final Colors

| Hex | Color | Category |
| --- | --- | --- |
| #ff9999 | Red | Bug |
| #cccccc | Gray | Not In Use |
| #84b6eb | Blue - Medium | Type |
| #c5def5 | Blue - Light | Not In Use |
| #c2e0c6 | Green | Gate |
| #fef2c0 | Yellow - Light | Priority |
| #ffa500 | Orange | Blocked |
