### ISSUE TITLE
Move deploy branch

### ISSUE THREAD

**Issue by dragan** [scipian/community#44]
Instead of having a separate branch for deployment in the `eve` repository, we're going to move it to two different locations. One location will be the public infra repository where the dev environment is located. It will be used as a demo/reference for deploying Scipian.

The other location will be our internal infra repo that we use to deploy our scipian environments.

**Comment by dragan** [comment]
@nicklathe Want to take this epic? If so, go through and estimate and drag to current when you work on an item.

**Comment by nicklathe** [comment]
@dragan Yep, will take this one.
