### ISSUE TITLE
Create ssh-controller repository

### ISSUE THREAD

**Issue by dragan** [scipian/community#5]
Before we can create any user story's around the ssh-controller, we first need a repository to create the issues in.

**Comment by dragan** [comment]
Use [our workflow](https://github.com/scipian/community/blob/master/CONTRIBUTING.md#creating-repositories) to create the repo and make sure it has these things inside of it.

- [x] LICENSE (https://github.com/scipian/ssh-controller/pull/1)
- [x] README.md (https://github.com/scipian/ssh-controller/pull/4)
- [x] CONTRIBUTING.md (https://github.com/scipian/ssh-controller/pull/2)
- [x] Issue Labels
- [x] Issue Templates (https://github.com/scipian/ssh-controller/pull/3)

**Comment by dragan** [comment]
@ncronquist Make sure you estimate the work for each PR. Also, we need the labels created to label the PR's.

**Comment by ncronquist** [comment]
@dragan I created the labels for the ssh-controller repo. For now I created them by pointing at the label packages in the Community repo. Should those label packages be added to the ssh-controller repo too or is the community repo the central source of truth for Scipian labels?

**Comment by ncronquist** [comment]
Also, sorry for having different PRs for each of the initial repository documents. Let me know if you would prefer me to merge the license, readme, and contributing into a single PR.

**Comment by dragan** [comment]
@ncronquist 

> @dragan I created the labels for the ssh-controller repo. For now I created them by pointing at the label packages in the Community repo. Should those label packages be added to the ssh-controller repo too or is the community repo the central source of truth for Scipian labels?

Nope, you did it correctly. The label packages stay in the community repo and we just point to them in the tool.

> Also, sorry for having different PRs for each of the initial repository documents. Let me know if you would prefer me to merge the license, readme, and contributing into a single PR.

No worries, it's fine to keep them as is.

**Comment by ncronquist** [comment]
@dragan @nicklathe As I created the [ssh-controller](https://github.com/scipian/ssh-controller) repo on GitHub, I'm currently an admin. I made both of you admins too. 

I tried to match all the settings to what we did in the Community repo, but I can't see those settings and I may have missed something. Would one of you mind validating the ssh-controller repo settings are correct? 

Then feel free to remove me as an admin :) Thanks!

**Comment by dragan** [comment]
> @dragan @nicklathe As I created the [ssh-controller](https://github.com/scipian/ssh-controller) repo on GitHub, I'm currently an admin. I made both of you admins too.
> 
> I tried to match all the settings to what we did in the Community repo, but I can't see those settings and I may have missed something. Would one of you mind validating the ssh-controller repo settings are correct?
> 
> Then feel free to remove me as an admin :) Thanks!

Okay, I created a new team called `maintainers` and added us to it. Next, I added the team to each repo with `admin` privileges. Everybody should have the necessary permissions now to mirror each repo.

**Comment by ncronquist** [comment]
[ssh-controller repo](https://github.com/scipian/ssh-controller) has been created with the initial base documents, issue templates, and issue labels. The repo settings have been setup to match the [community repo](https://github.com/scipian/community) settings.
